### ISSUE TITLE
Instagram still blocks accounts

### ISSUE THREAD

**Issue by gitgudscrap** [suyashjawale/InstagramCLI#1]
As the title indicates, instagram blocks my account when I try to grab a user's followers list with 10k+ items, it stops at around 4.5k. I tried putting a 4-second sleep timer in between iterations under get_users method, but no luck. I also couldn't continue the list from where it stopped by setting next_max_id to (number of followers grabber/12).

Do you have any suggestions?

**Comment by suyashjawale** [comment]
I tried this, but encountered the same issue . Got blocked after iteration 765. 
![Screenshot (84)](https://user-images.githubusercontent.com/58392029/140263518-9bfd46ea-185b-46e6-9d19-20944321a8df.png)

Will try grabbing the next_max_id from where it stopped and then use it with different account. Will reply in the thread if any success. Cause if I try to use proxy or change user-agent that wont work as mentioned in this  [issue](https://stackoverflow.com/questions/69111471/how-do-i-send-a-request-after-being-blocked-in-instagram)

**Comment by suyashjawale** [comment]
@gitgudscrap After getting blocked from 2 accounts. Finally I tried testing it manually. Turns out that even if I keep scrolling the followers list on Instagram manually, it will still block after 4k followers. Have posted the screenshots below. Furthermore, I'm changing the repo description and removing the "prevents from getting blocked" clause. 

You can close the issue now. 

Results for manual testing.

![ss2](https://user-images.githubusercontent.com/58392029/141290122-25e653ea-878c-4d7c-9053-01d5e1a3628c.PNG)

![ss1](https://user-images.githubusercontent.com/58392029/141290202-52d3720e-5f2c-427d-8dee-382acd5cb2ad.PNG)
